### ISSUE TITLE
Inputting our own sentence

### ISSUE THREAD

**Issue by humehta** [cmward/hobbs#2]
Hey,
How can we input our own sentence as I tried inserting my own sentence but it gives an error of Grammar does not support some input words?

**Comment by cmward** [comment]
Apologies - it's been a while since I've worked with any NLTK code at this point. If you're inputting parsed sentences and getting that error, you may have to download more [NLTK treebank data](http://www.nltk.org/data.html).

This code is really only suitable for learning about Hobbs' algorithm. If you're looking for production quality, I'd recommend Hugging Face's [neuralcoref](https://github.com/huggingface/neuralcoref) or [CoreNLP](https://stanfordnlp.github.io/CoreNLP/coref.html). 

I'll close this for now, but feel free to reopen if you want to share some more specific details about the error you're encountering, and I can try to help you out.
